#! /bin/sh

workdir=$PWD
srcdir=$(dirname "$(readlink -f "$0")")
image_name=1minutetip-in-container

set -e

if ! podman inspect "$image_name" 2>/dev/null >/dev/null; then
(
    set -x
    cd "$srcdir" || exit 1
    echo "building in $PWD"
    docker build -t "$image_name" .
)
fi

name=$(id -u -n)

conf_dir=$HOME/.1minutetip

mkdir -p "$conf_dir"
chcon -R -t svirt_sandbox_file_t "$conf_dir"

exec podman run -e USERNAME="$name" --rm -ti \
    -e HOME=/confdir \
    -v "$conf_dir:/confdir/.1minutetip" \
    "$image_name" 1minutetip "$@"
